import { CheckCircle2, Clock } from "lucide-react";
import Breadcrumb from "../components/Breadcrumb";
import VideoGuide from "../components/VideoGuide";
import RelatedArticles from "../components/RelatedArticles";
import HelpFooter from "../components/HelpFooter";

export default function ProfileArticle() {
  const relatedArticles = [
    { title: "Two-Step Verification", description: "Add an extra layer of security to your account.", path: "/account/two-step-verification", readTime: "4 min" },
    { title: "Managing Team Members", description: "Invite and manage roles for your team.", path: "/account/team-members", readTime: "6 min" },
    { title: "Privacy Settings", description: "Control what data TallyApp stores and shares.", path: "/account/privacy", readTime: "3 min" }
  ];

  return (
    <div className="max-w-3xl mx-auto px-4 md:px-8 py-8">
      <Breadcrumb items={[{ label: "Account", path: "/account" }, { label: "Profile & Business Info" }]} />

      <div className="mb-2 flex items-center gap-2">
        <Clock size={12} className="text-[#A1A1AA]" />
        <span className="text-xs text-[#A1A1AA]">Updated June 2026</span>
        <span className="text-[#27272A]">·</span>
        <span className="text-xs text-[#A1A1AA]">3 min read</span>
      </div>

      <h1 className="text-white text-3xl font-bold mb-6 leading-tight">Profile & Business Info</h1>
      
      <p className="text-[#A1A1AA] text-[15px] leading-relaxed mb-6">
        Keep your business information up to date. Your business profile details are vital because they 
        appear on all invoices, receipts, and reports generated by TallyApp. Ensure your contact details 
        and branding are accurate to maintain a professional appearance.
      </p>

      <VideoGuide
        title="Updating Your Profile"
        subtitle="Learn how to quickly edit your business info and logo"
        duration="1:55"
      />

      <div className="mt-10 mb-8">
        <h2 className="text-white text-xl font-semibold mb-6">Steps to Check or Edit Your Profile</h2>
        
        <div className="space-y-6 mb-10">
          <div className="flex gap-4">
            <div className="flex-shrink-0 w-7 h-7 rounded-full bg-[#22D3EE]/15 border border-[#22D3EE]/30 flex items-center justify-center text-[#22D3EE] text-xs font-bold mt-0.5">1</div>
            <div>
              <p className="text-white font-semibold text-[15px] mb-1">Open Account Settings</p>
              <p className="text-[#A1A1AA] text-sm leading-relaxed">
                From the main dashboard, tap the <strong>Profile Icon</strong> in the top-right corner to access your Account Settings.
              </p>
            </div>
          </div>
          <div className="flex gap-4">
            <div className="flex-shrink-0 w-7 h-7 rounded-full bg-[#22D3EE]/15 border border-[#22D3EE]/30 flex items-center justify-center text-[#22D3EE] text-xs font-bold mt-0.5">2</div>
            <div>
              <p className="text-white font-semibold text-[15px] mb-1">Select Business Profile</p>
              <p className="text-[#A1A1AA] text-sm leading-relaxed">
                Tap on <strong>Business Profile</strong>. Here, you will see your current business name, logo, address, and contact details.
              </p>
            </div>
          </div>
          <div className="flex gap-4">
            <div className="flex-shrink-0 w-7 h-7 rounded-full bg-[#22D3EE]/15 border border-[#22D3EE]/30 flex items-center justify-center text-[#22D3EE] text-xs font-bold mt-0.5">3</div>
            <div>
              <p className="text-white font-semibold text-[15px] mb-1">Edit Information</p>
              <p className="text-[#A1A1AA] text-sm leading-relaxed">
                Tap on any field such as <strong>Business Name</strong>, <strong>Phone Number</strong>, or <strong>Email Address</strong> to make changes. You can also tap your logo to upload a new image from your device.
              </p>
            </div>
          </div>
          <div className="flex gap-4">
            <div className="flex-shrink-0 w-7 h-7 rounded-full bg-[#22D3EE]/15 border border-[#22D3EE]/30 flex items-center justify-center text-[#22D3EE] text-xs font-bold mt-0.5">4</div>
            <div>
              <p className="text-white font-semibold text-[15px] mb-1">Save Changes</p>
              <p className="text-[#A1A1AA] text-sm leading-relaxed">
                Once you are satisfied with your updates, tap the <strong>Save</strong> button at the bottom of the screen. Your changes will immediately reflect across all your future invoices and reports.
              </p>
            </div>
          </div>
        </div>

        <div className="p-5 rounded-xl border border-[#22D3EE]/30 bg-[#22D3EE]/5 flex items-center justify-between">
           <div>
             <h3 className="text-white font-semibold mb-1">Need to manage multiple entities?</h3>
             <p className="text-[#A1A1AA] text-sm">You must switch to the respective entity from the dropdown before editing its profile.</p>
           </div>
        </div>
      </div>

      <RelatedArticles articles={relatedArticles} />
      <HelpFooter />
    </div>
  );
}
